[package]
name = "session-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
dirs-next = "2"
eframe = { version = "0.27" }
egui = "0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
